version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
        - 8000:80
        - 8001:443 
    build:
      context: .
      dockerfile: API/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: "Qwe123!@#"
        ACCEPT_EULA: "Y"
